---
deployment:
  tasks:
    # Set deployment path to public_html
    - export DEPLOYPATH=/home/$USER/public_html/
    
    # Create necessary directories outside public_html
    - /bin/mkdir -p /home/$USER/app_data
    - /bin/mkdir -p /home/$USER/logs
    
    # Copy main application files to public_html
    - /bin/cp -R WebApplication1/* $DEPLOYPATH
    
    # Copy database to app_data (outside public_html for security)
    - /bin/cp WebApplication1/app.db /home/$USER/app_data/ 2>/dev/null || true
    
    # Copy configuration files
    - /bin/cp WebApplication1/web.config $DEPLOYPATH 2>/dev/null || true
    - /bin/cp WebApplication1/appsettings.Production.json $DEPLOYPATH 2>/dev/null || true
    
    # Copy static content from wwwroot to root of public_html
    - /bin/cp -R WebApplication1/wwwroot/* $DEPLOYPATH 2>/dev/null || true
    
    # Set proper file permissions
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \; 2>/dev/null || true
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \; 2>/dev/null || true
    
    # Create .htaccess for URL rewriting and security
    - /bin/cat > $DEPLOYPATH/.htaccess << 'HTACCESS_END'
RewriteEngine On

# Handle ASP.NET Core routing
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.html [QSA,L]

# Security headers
Header always set X-Content-Type-Options nosniff
Header always set X-Frame-Options DENY
Header always set X-XSS-Protection "1; mode=block"

# Hide sensitive directories
RedirectMatch 403 ^/bin/.*$
RedirectMatch 403 ^/App_Data/.*$
RedirectMatch 403 ^/logs/.*$

# Cache static files
<FilesMatch "\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$">
    ExpiresActive On
    ExpiresDefault "access plus 30 days"
    Header set Cache-Control "public, max-age=2592000"
</FilesMatch>
HTACCESS_END